#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
格式管理器 - 管理多种输出格式
"""

import json
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime


class FormatManager:
    """格式管理器"""
    
    SUPPORTED_FORMATS = ["markdown", "json", "yaml", "html", "keepachangelog"]
    
    def __init__(self, config: Optional[Dict] = None):
        """初始化格式管理器"""
        self.config = config or {}
    
    def format_changelog(
        self,
        changelog_data: Dict,
        format_type: str = "markdown"
    ) -> str:
        """
        格式化变更日志
        
        Args:
            changelog_data: 变更日志数据
            format_type: 输出格式
        
        Returns:
            格式化后的字符串
        """
        if format_type == "markdown":
            return self._format_markdown(changelog_data)
        elif format_type == "json":
            return self._format_json(changelog_data)
        elif format_type == "yaml":
            return self._format_yaml(changelog_data)
        elif format_type == "html":
            return self._format_html(changelog_data)
        elif format_type == "keepachangelog":
            return self._format_keepachangelog(changelog_data)
        else:
            return self._format_markdown(changelog_data)
    
    def _format_markdown(self, data: Dict) -> str:
        """格式化为Markdown"""
        lines = []
        
        # 标题
        lines.append("# API Changelog")
        lines.append("")
        
        # 版本
        version = data.get("version", "Unreleased")
        date = data.get("date", datetime.now().strftime("%Y-%m-%d"))
        lines.append(f"## [{version}] - {date}")
        lines.append("")
        
        # 变更类型
        changes = data.get("changes", {})
        
        type_titles = {
            "major": "💥 Breaking Changes",
            "minor": "✨ New Features",
            "patch": "🐛 Bug Fixes",
            "deprecated": "⚠️ Deprecations",
            "removed": "🗑️ Removed",
            "security": "🔒 Security",
            "performance": "⚡ Performance",
            "documentation": "📝 Documentation",
        }
        
        for change_type, title in type_titles.items():
            if change_type in changes and changes[change_type]:
                lines.append(f"### {title}")
                lines.append("")
                
                for change in changes[change_type]:
                    lines.append(f"- {change}")
                
                lines.append("")
        
        # 页脚
        lines.append("---")
        lines.append("*Generated by APIChangelog-Pilot*")
        
        return "\n".join(lines)
    
    def _format_json(self, data: Dict) -> str:
        """格式化为JSON"""
        output = {
            "generated_at": datetime.now().isoformat(),
            "version": data.get("version", "Unreleased"),
            "date": data.get("date", datetime.now().strftime("%Y-%m-%d")),
            "changes": data.get("changes", {})
        }
        
        return json.dumps(output, indent=2, ensure_ascii=False)
    
    def _format_yaml(self, data: Dict) -> str:
        """格式化为YAML"""
        try:
            import yaml
            
            output = {
                "changelog": {
                    "version": data.get("version", "Unreleased"),
                    "date": data.get("date", datetime.now().strftime("%Y-%m-%d")),
                    "changes": data.get("changes", {})
                }
            }
            
            return yaml.dump(output, default_flow_style=False, allow_unicode=True)
        except ImportError:
            # 如果没有yaml库，返回JSON
            return self._format_json(data)
    
    def _format_html(self, data: Dict) -> str:
        """格式化为HTML"""
        markdown = self._format_markdown(data)
        
        # 简单的Markdown转HTML
        html = markdown
        
        # 标题
        html = html.replace("# ", "<h1>").replace("\n", "</h1>\n", 1)
        html = html.replace("## ", "<h2>").replace("\n", "</h2>\n")
        html = html.replace("### ", "<h3>").replace("\n", "</h3>\n")
        
        # 列表
        html = html.replace("- ", "<li>")
        html = html.replace("</h3>\n<li>", "</h3>\n<ul><li>")
        html = html + "\n</ul>"
        
        # 分隔线
        html = html.replace("---", "<hr>")
        
        # 包装
        full_html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Changelog</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            line-height: 1.6;
        }}
        h1, h2, h3 {{ color: #333; }}
        h1 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        ul {{ list-style-type: none; padding-left: 0; }}
        li {{ margin: 8px 0; }}
        hr {{ border: none; border-top: 1px solid #eee; margin: 20px 0; }}
        .breaking {{ color: #d9534f; }}
    </style>
</head>
<body>
{html}
</body>
</html>"""
        
        return full_html
    
    def _format_keepachangelog(self, data: Dict) -> str:
        """格式化为Keep a Changelog格式"""
        lines = []
        
        lines.append("# Changelog")
        lines.append("")
        lines.append("All notable changes to this project will be documented in this file.")
        lines.append("")
        lines.append("The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),")
        lines.append("and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).")
        lines.append("")
        
        # 版本
        version = data.get("version", "Unreleased")
        date = data.get("date", datetime.now().strftime("%Y-%m-%d"))
        
        if version == "Unreleased":
            lines.append("## [Unreleased]")
        else:
            lines.append(f"## [{version}] - {date}")
        
        lines.append("")
        
        # 变更
        changes = data.get("changes", {})
        
        sections = [
            ("added", "Added"),
            ("changed", "Changed"),
            ("deprecated", "Deprecated"),
            ("removed", "Removed"),
            ("fixed", "Fixed"),
            ("security", "Security"),
        ]
        
        for key, title in sections:
            if key in changes and changes[key]:
                lines.append(f"### {title}")
                lines.append("")
                
                for change in changes[key]:
                    lines.append(f"- {change}")
                
                lines.append("")
        
        return "\n".join(lines)
    
    def save_changelog(
        self,
        content: str,
        filename: str,
        format_type: str = "markdown"
    ):
        """保存变更日志到文件"""
        path = Path(filename)
        
        # 确保目录存在
        path.parent.mkdir(parents=True, exist_ok=True)
        
        # 根据格式设置扩展名
        extensions = {
            "markdown": ".md",
            "json": ".json",
            "yaml": ".yaml",
            "html": ".html",
        }
        
        if not path.suffix:
            path = path.with_suffix(extensions.get(format_type, ".md"))
        
        # 写入文件
        path.write_text(content, encoding="utf-8")
        
        return str(path)
